# Generated by Django 3.1.4 on 2021-03-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysagile', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
